### ISSUE TITLE
工程目录/ios下没有flutter_no_cpp_src.podspec文件

### ISSUE THREAD

**Issue by mr-52hz** [CaiJingLong/example_for_flutter_ffi#1]
非常感谢，能够看到这么详细的ffi在flutter中的应用。但是我在还原ios项目时遇到了一个问题：当我按照文档，执行完sh生成framework之后，在ios目录中没有.podspec文件，而且也没有相关说明来创建文档。我查阅文档试过`pod init` `pod create flutter_no_cpp_src.podspec` `pod lib lint flutter_no_cpp_src.podspec`但是一直报错，无法引入some.framework。
这是错误信息
<img width="800" alt="截屏2020-01-20下午2 04 26" src="https://user-images.githubusercontent.com/40566893/72702686-8de1c600-3b8e-11ea-9287-f0a8ba9e3e9b.png">

**Comment by CaiJingLong** [comment]
podspec 是创建项目时自带的 
使用`$ flutter create -t plugin project_name ` 创建的时候带上的

可能是文章中漏写了,  本系列第一篇写了, 但是第二篇没写

**Comment by CaiJingLong** [comment]
你如果写过flutter插件就应该知道本篇的其他目录结构是标准的插件目录结构

本篇除cpp部分外, 其余使用的是flutter默认配置

**Comment by mr-52hz** [comment]
好的 感谢！新年快乐！
